import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";

const outfit = Outfit({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Invoicely",
  description: "Generated by create next app",
icons:{
  icon:"/favicon.ico",
  apple:"/apple-touch-icon.png",
}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full w-full overflow-x-hidden", "antialiased", geistSans.variable, geistMono.variable, "font-sans", outfit.variable)}
    >
      <SessionProvider >

      <body className="min-h-full flex flex-col text-black">{children}</body>
      </SessionProvider>
    </html>
  );
}
